<?php
// Tableau contenant l'annuaire interne des personnels de l'IUT (en attendant de l'extraire directement de la base de données)
$annuaireInterne = [
    ['nom' => "AGERON", 'prénom' => "Blandine", 'poste' => "831", 'bureau' => "A115", 'fonction' => "TC, Chef de Département"],
    ['nom' => "AMBLARD", 'prénom' => "Marion", 'poste' => "854", 'bureau' => "C104", 'fonction' => "R&T, Responsable LP MAC et LP Vitivinicole"],
    ['nom' => "ARSHAKIAN", 'prénom' => "Robik", 'poste' => "846", 'bureau' => "A109", 'fonction' => "Scolarité centrale"],
    ['nom' => "AZNAR", 'prénom' => "Céline", 'poste' => "850", 'bureau' => "C108", 'fonction' => "Secrétariat R&T + LP ASUR"],
    ['nom' => "BARBOT", 'prénom' => "Gildas", 'poste' => "832", 'bureau' => "A212", 'fonction' => "TC, Responsable LP ECMN"],
    ['nom' => "BENEFICE", 'prénom' => "Claire", 'poste' => "855", 'bureau' => "E006", 'fonction' => "IAE"],
    ['nom' => "BERGERON", 'prénom' => "Karine", 'poste' => "865", 'bureau' => "C105", 'fonction' => "R&T, Directrice des Etudes 2ème année, Responsable Poursuite d'études"],
    ['nom' => "BERTHOZ", 'prénom' => "Marion", 'poste' => "858", 'bureau' => "A117", 'fonction' => "Gestion des charges d'enseignement (HC)"],
    ['nom' => "BESSON", 'prénom' => "Béatrice", 'poste' => "830", 'bureau' => "A114", 'fonction' => "Secrétariat TC1 + Année Spéciale"],
    ['nom' => "BONNEFOND", 'prénom' => "Céline", 'poste' => "814", 'bureau' => "A110", 'fonction' => "GEA, Directrice des Etudes 2ème année"],
    ['nom' => "BOSSAN", 'prénom' => "Marie-Pierre", 'poste' => "855", 'bureau' => "E006", 'fonction' => "TC, Responsable L3 Eco.-Gestion Parcours Management"],
    ['nom' => "BOULLE", 'prénom' => "Didier", 'poste' => "818", 'bureau' => "B115", 'fonction' => "INFO, Responsable projets 2ème année"],
    ['nom' => "BOYER", 'prénom' => "Julien", 'poste' => "883", 'bureau' => "A003-B", 'fonction' => "Communication (Apprenti)"],
    ['nom' => "BRUNET", 'prénom' => "Bernard", 'poste' => "867", 'bureau' => "D012", 'fonction' => "TC, Responsable des projets"],
    ['nom' => "CARROUE", 'prénom' => "Nathalie", 'poste' => "887", 'bureau' => "E012", 'fonction' => "Secrétariat IAE/IUT, L3 Management"],
    ['nom' => "CARSANA", 'prénom' => "Laurence", 'poste' => "876", 'bureau' => "E009", 'fonction' => "IAE - Responsable M2 Parcours Communication et digitale"],
    ['nom' => "CEYSSON", 'prénom' => "Christelle", 'poste' => "870", 'bureau' => "E011", 'fonction' => "Secrétariat IAE, M1 et M2 du chiffre"],
    ['nom' => "CHARENSOL", 'prénom' => "Sylvain", 'poste' => "835", 'bureau' => "B119", 'fonction' => "INFO, Directeur des Etudes 1ère année"],
    ['nom' => "CHECHAT", 'prénom' => "David", 'poste' => "837", 'bureau' => "B109", 'fonction' => "CRI"],
    ['nom' => "CHOKOR", 'prénom' => "Ahmad", 'poste' => "878", 'bureau' => "E007", 'fonction' => "IAE"],
    ['nom' => "CONSTANT", 'prénom' => "Blandine", 'poste' => "836", 'bureau' => "B114", 'fonction' => "INFO"],
    ['nom' => "CORNU ", 'prénom' => "Christelle", 'poste' => "875", 'bureau' => "D001", 'fonction' => "GEA"],
    ['nom' => "DEGUILHEM", 'prénom' => "Anne", 'poste' => "810", 'bureau' => "B008", 'fonction' => "Pôle Licences, Responsable Administratif"],
    ['nom' => "DELABALLE", 'prénom' => "Grégory", 'poste' => "806", 'bureau' => "A109", 'fonction' => "Responsable Scolarité centrale"],
    ['nom' => "DE SAUZA", 'prénom' => "Guillaume", 'poste' => "828", 'bureau' => "B120", 'fonction' => "INFO, Responsable Emploi du temps (EDT)"],
    ['nom' => "DESPIERRE-CORPORON", 'prénom' => "Gaëlle", 'poste' => "859", 'bureau' => "A205", 'fonction' => "TC"],
    ['nom' => "DEXPERT", 'prénom' => "Magali", 'poste' => "857", 'bureau' => "B015", 'fonction' => "TC"],
    ['nom' => "DIAGANA", 'prénom' => "Dominique", 'poste' => "829", 'bureau' => "A114", 'fonction' => "Secrétariat TC2"],
    ['nom' => "DREMONT", 'prénom' => "Arnaud", 'poste' => "864", 'bureau' => "A000", 'fonction' => "Service technique"],
    ['nom' => "DREXLER", 'prénom' => "Anouk", 'poste' => "897", 'bureau' => "D002", 'fonction' => "GEA, Responsable LP MGCRC"],
    ['nom' => "DROIT", 'prénom' => "Olivier", 'poste' => "867", 'bureau' => "D012", 'fonction' => "TC, Chargé de mission Entreprenariat"],
    ['nom' => "DUCCINI", 'prénom' => "Christian", 'poste' => "862", 'bureau' => "C106 / A017", 'fonction' => "Directeur Adjoint"],
    ['nom' => "DUFLOT", 'prénom' => "Annie", 'poste' => "836", 'bureau' => "B114", 'fonction' => "GEA"],
    ['nom' => "FAUDOT", 'prénom' => "Adrien", 'poste' => "859", 'bureau' => "A205", 'fonction' => "GEA, Responsable PPP"],
    ['nom' => "FLOURY-GUEPIN", 'prénom' => "Claire", 'poste' => "827", 'bureau' => "A015", 'fonction' => "Communication, Relations Internationales, Club Passerelle"],
    ['nom' => "FOURTY", 'prénom' => "Nicolas", 'poste' => "851", 'bureau' => "C107", 'fonction' => "R&T, Chef de Département"],
    ['nom' => "GALDON", 'prénom' => "Christine", 'poste' => "861", 'bureau' => "C002", 'fonction' => "Secrétariat Relations Internationales"],
    ['nom' => "GALDON", 'prénom' => "Serge", 'poste' => "885", 'bureau' => "D011", 'fonction' => "GEA, Responsable Liaison Lycée Université (LLU)"],
    ['nom' => "GARCIN", 'prénom' => "François", 'poste' => "832", 'bureau' => "A212", 'fonction' => "GEA"],
    ['nom' => "GAY", 'prénom' => "Simon", 'poste' => "857", 'bureau' => "B015", 'fonction' => "GEA"],
    ['nom' => "GEINDRE", 'prénom' => "Sébastien", 'poste' => "871", 'bureau' => "E008", 'fonction' => "Directeur site IAE Valence, Responsable M1 du chiffre"],
    ['nom' => "GENON-CATALOT", 'prénom' => "Denis", 'poste' => "863", 'bureau' => "C103", 'fonction' => "R&T, Responsable LP ASUR"],
    ['nom' => "GENTHIAL", 'prénom' => "Damien", 'poste' => "839", 'bureau' => "B108", 'fonction' => "INFO, Responsable CRI, Directeur des Etudes 2ème année"],
    ['nom' => "GIACOMONI", 'prénom' => "Jessica", 'poste' => "826", 'bureau' => "A113", 'fonction' => "TC, Directrice des Etudes 1ère et 2ème années"],
    ['nom' => "GIORDANO", 'prénom' => "Karine", 'poste' => "840", 'bureau' => "B112", 'fonction' => "Secrétariat INFO + LP CASIR"],
    ['nom' => "GORY", 'prénom' => "Béatrice", 'poste' => "820", 'bureau' => "A111", 'fonction' => "Secrétariat GEA2ème année"],
    ['nom' => "GOUTERON", 'prénom' => "Caroline", 'poste' => "815", 'bureau' => "B005", 'fonction' => "Secrétariat LP ABF, LP Logistique, L3 Adjoint de direction, LP Créa/Rep. Pme-Pmi"],
    ['nom' => "GUICHARD", 'prénom' => "Laurence", 'poste' => "800", 'bureau' => "A002", 'fonction' => "Accueil"],
    ['nom' => "HAMMAMI", 'prénom' => "Hayet", 'poste' => "875", 'bureau' => "D001", 'fonction' => "GEA"],
    ['nom' => "JAMONT", 'prénom' => "Jean-Paul", 'poste' => "852", 'bureau' => "C109", 'fonction' => "R&T"],
    ['nom' => "JARNIAS", 'prénom' => "Sylvie", 'poste' => "832", 'bureau' => "A212", 'fonction' => "GEA, Responsable L3 Adjoint de direction, Responsable LP PME-PMI FC"],
    ['nom' => "JEAN", 'prénom' => "Sebastien", 'poste' => "834", 'bureau' => "B111", 'fonction' => "INFO"],
    ['nom' => "JONVAL", 'prénom' => "Laurette", 'poste' => "882", 'bureau' => "A003-B", 'fonction' => "Gestion des vacataires, Secrétariat DU CA"],
    ['nom' => "JONVAL", 'prénom' => "Laurette", 'poste' => "800", 'bureau' => "A002", 'fonction' => "Accueil"],
    ['nom' => "JOUBERT", 'prénom' => "Francette", 'poste' => "808", 'bureau' => "A008", 'fonction' => "Reprographie"],
    ['nom' => "JUBAN", 'prénom' => "Jean-Yves", 'poste' => "801", 'bureau' => "A120", 'fonction' => "Directeur de l'IUT"],
    ['nom' => "JUNEK ", 'prénom' => "Françoise", 'poste' => "869", 'bureau' => "A004", 'fonction' => "Communication"],
    ['nom' => "JUNEK ", 'prénom' => "Martine", 'poste' => "847", 'bureau' => "A109", 'fonction' => "Scolarité centrale"],
    ['nom' => "KARCHER", 'prénom' => "Stéphanie", 'poste' => "822", 'bureau' => "B006", 'fonction' => "TC"],
    ['nom' => "LAMAUD", 'prénom' => "Christelle", 'poste' => "877", 'bureau' => "C003", 'fonction' => "TC, Co-Responsables des Relations Internationales, Responsable TOEIC"],
    ['nom' => "LAMBERT", 'prénom' => "Victor", 'poste' => "821", 'bureau' => "A112", 'fonction' => "GEA, Chef de Département, Directeur des Etudes 1ère année"],
    ['nom' => "LIEVIN", 'prénom' => "Romain", 'poste' => "863", 'bureau' => "C103", 'fonction' => "R&T"],
    ['nom' => "LORRAIN", 'prénom' => "Nathalie", 'poste' => "833", 'bureau' => "D010", 'fonction' => "TC, Responsable des stages 1ère année"],
    ['nom' => "LUCCI", 'prénom' => "Alain", 'poste' => "834", 'bureau' => "B111", 'fonction' => "INFO, Responsable Poursuite d'études"],
    ['nom' => "MABED", 'prénom' => "Abdelmalek", 'poste' => "803", 'bureau' => "A122", 'fonction' => "Directeur Administratif"],
    ['nom' => "MADIES", 'prénom' => "Anne", 'poste' => "859", 'bureau' => "A205", 'fonction' => "GEA, Respnsable Année Spéciale"],
    ['nom' => "MADIES", 'prénom' => "Philippe", 'poste' => "878", 'bureau' => "E007", 'fonction' => "IAE, Responsable M2 Banque Finance"],
    ['nom' => "MARTINS", 'prénom' => "Geneviève", 'poste' => "813", 'bureau' => "B009", 'fonction' => "Secrétariat LP MGCRC, LP MAC, LP Vitivinicole, LP ECMN"],
    ['nom' => "MAUPETIT", 'prénom' => "Séverine", 'poste' => "824", 'bureau' => "A113", 'fonction' => "TC, Responsable Emploi du temps (EDT), TS, Parcours Sup"],
    ['nom' => "MENS", 'prénom' => "Carole", 'poste' => "833", 'bureau' => "D010", 'fonction' => "TC, Responsable des stages 2ème année"],
    ['nom' => "MERCIER", 'prénom' => "Annabelle", 'poste' => "841", 'bureau' => "B113", 'fonction' => "INFO, Chef de Département"],
    ['nom' => "METGE", 'prénom' => "Cécile", 'poste' => "828", 'bureau' => "B120", 'fonction' => "INFO"],
    ['nom' => "MICHEL", 'prénom' => "Frédéric", 'poste' => "854", 'bureau' => "C104", 'fonction' => "R&T, Responsable des projets et des stages 2ème année, Responsable Club Passerelle"],
    ['nom' => "MICHEL", 'prénom' => "Mickaël", 'poste' => "805", 'bureau' => "A118", 'fonction' => "Secrétariat Service Financier"],
    ['nom' => "MOLLIEX", 'prénom' => "Raphaël", 'poste' => "865", 'bureau' => "C105", 'fonction' => "R&T, Directeur des Etudes 1ère année, Responsable Emploi du temps (EDT)"],
    ['nom' => "NOUYRIGAT", 'prénom' => "Geneviève", 'poste' => "845", 'bureau' => "B016", 'fonction' => "GEA"],
    ['nom' => "OBJOIS", 'prénom' => "Philippe", 'poste' => "818", 'bureau' => "B115", 'fonction' => "INFO, Responsable des stages"],
    ['nom' => "OCCELLO", 'prénom' => "Michel", 'poste' => "809", 'bureau' => "D003", 'fonction' => "INFO"],
    ['nom' => "PATRIZI", 'prénom' => "Amélie", 'poste' => "859", 'bureau' => "A205", 'fonction' => "GEA"],
    ['nom' => "PERSE", 'prénom' => "Joackim", 'poste' => "812", 'bureau' => "B108", 'fonction' => "CRI"],
    ['nom' => "PEYREMORTE", 'prénom' => "Eric", 'poste' => "837", 'bureau' => "B109", 'fonction' => "CRI"],
    ['nom' => "POURRET", 'prénom' => "Séverine", 'poste' => " - ", 'bureau' => "E005", 'fonction' => "Directrice maintenance et logistique"],
    ['nom' => "PROVILLARD", 'prénom' => "Patrick", 'poste' => "897", 'bureau' => "D002", 'fonction' => "GEA"],
    ['nom' => "RAIEVSKY", 'prénom' => "Clément", 'poste' => "835", 'bureau' => "B119", 'fonction' => "INFO, Responsable LP CASIR"],
    ['nom' => "RANDRIANIRINA", 'prénom' => "Iony", 'poste' => "885", 'bureau' => "D011", 'fonction' => "GEA"],
    ['nom' => "RENAUDET", 'prénom' => "Stéphane", 'poste' => "812", 'bureau' => "B108", 'fonction' => "CRI"],
    ['nom' => "REYDET", 'prénom' => "Sabine", 'poste' => "807", 'bureau' => "A017", 'fonction' => "Directrice adjointe, TC"],
    ['nom' => "ROBERT", 'prénom' => "Nicolas", 'poste' => "877", 'bureau' => "C003", 'fonction' => "GEA, Co-Responsable des Relations Internationales, Resp. des stages 1ère et 2ème années et du DU Business Management"],
    ['nom' => "ROSZAK", 'prénom' => "Anne", 'poste' => "802", 'bureau' => "A121", 'fonction' => "Assistante de direction"],
    ['nom' => "ROUMEAS", 'prénom' => "Fabienne", 'poste' => "857", 'bureau' => "B015", 'fonction' => "TC"],
    ['nom' => "SANCHEZ", 'prénom' => "Indrani", 'poste' => "881", 'bureau' => "A003", 'fonction' => "Responsable du Centre Compétences et Métiers (CCM)"],
    ['nom' => "SASSOLAS", 'prénom' => "Delphine", 'poste' => "885", 'bureau' => "D011", 'fonction' => "GEA, Responsable projets 2ème année, co-Responsable LP ABF"],
    ['nom' => "SAUREL", 'prénom' => "Marik", 'poste' => "890", 'bureau' => "A010", 'fonction' => "Bibliothèque"],
    ['nom' => "SCHUSSLER", 'prénom' => "Christine", 'poste' => "819", 'bureau' => "A111", 'fonction' => "Secrétariat GEA1ère année + Année spéciale"],
    ['nom' => "TREMOUILHAC", 'prénom' => "Cédric", 'poste' => "879", 'bureau' => "A211", 'fonction' => "GEA, co-Responsable LP ABF"],
    ['nom' => "VALLOT", 'prénom' => "Lugdivine", 'poste' => "845", 'bureau' => "B016", 'fonction' => "TC"],
    ['nom' => "VARIN", 'prénom' => "Christelle", 'poste' => "822", 'bureau' => "B006", 'fonction' => "TC, Responsable Année Spéciale"],
    ['nom' => "VAUX", 'prénom' => "Cécile", 'poste' => "804", 'bureau' => "A116", 'fonction' => "Responsable Service Financier"],
    ['nom' => "VERMOTE", 'prénom' => "Laure", 'poste' => "872", 'bureau' => "E011", 'fonction' => "Secrétariat et Accueil IAE, M1 et M2 Marketing, LP Pme-Pmi FC"],
    ['nom' => "VIALLET", 'prénom' => "Isabelle", 'poste' => "816", 'bureau' => "B007", 'fonction' => "Formation Continue, Alternance, Secrétariat DU CA"],
    ['nom' => "VINCENT", 'prénom' => "Thierry", 'poste' => "811", 'bureau' => "A211", 'fonction' => "GEA, Responsable DU Créateur d'activités, Référent handicap"],
    ['nom' => "WILHELM", 'prénom' => "Marie-Claire", 'poste' => "876", 'bureau' => "E009", 'fonction' => "IAE, Responsable M1 Marketing"],
    ['nom' => "ZOUARI", 'prénom' => "Dorsaf", 'poste' => "822", 'bureau' => "B006", 'fonction' => "GEA - Responsable LP Logistique"],
];


// Affiche une des lignes de l'annuaire interne dans une ligne (row) d'un tableau HTML
function uneLigneHTML(array $personne): string
{
    $html = "<tr>";
    foreach ($personne as $value) {
        $html .= '<td>' . $value . '</td>';
    }
    return $html . "</tr>";
}
